--
-- PostgreSQL database dump
--

\restrict O2bKGsRucduv3OrUidLxw60wCb6OL0nvCNT02xkaJTnNzVfK2libjuHLAVXoMFr

-- Dumped from database version 17.6 (Debian 17.6-1.pgdg12+1)
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: lubricantes_db_30om_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO lubricantes_db_30om_user;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: lubricantes_db_30om_user
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ProductosCompras_historialstock; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public."ProductosCompras_historialstock" (
    id bigint NOT NULL,
    fecha timestamp with time zone NOT NULL,
    stock_antes numeric(12,2) NOT NULL,
    stock_despues numeric(12,2) NOT NULL,
    costo_promedio_antes numeric(12,2) NOT NULL,
    costo_promedio_despues numeric(12,2) NOT NULL,
    costo_unitario_compra numeric(10,2) NOT NULL,
    costo_unitario_anterior numeric(10,2),
    usuario_id bigint NOT NULL,
    movimiento_id bigint NOT NULL
);


ALTER TABLE public."ProductosCompras_historialstock" OWNER TO lubricantes_db_30om_user;

--
-- Name: ProductosCompras_historialstock_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public."ProductosCompras_historialstock" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductosCompras_historialstock_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductosCompras_movimientoinventario; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public."ProductosCompras_movimientoinventario" (
    id bigint NOT NULL,
    tipo character varying(10) NOT NULL,
    cantidad numeric(10,3) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    referencia character varying(100) NOT NULL,
    observaciones text NOT NULL,
    costo_unitario numeric(10,2),
    articulo_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    proveedor_id bigint
);


ALTER TABLE public."ProductosCompras_movimientoinventario" OWNER TO lubricantes_db_30om_user;

--
-- Name: ProductosCompras_movimientoinventario_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public."ProductosCompras_movimientoinventario" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductosCompras_movimientoinventario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductosCompras_proveedor; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public."ProductosCompras_proveedor" (
    id bigint NOT NULL,
    nombre character varying(200) NOT NULL,
    rfc character varying(20) NOT NULL,
    contacto character varying(100) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    direccion text NOT NULL,
    activo boolean NOT NULL,
    creado_en timestamp with time zone NOT NULL
);


ALTER TABLE public."ProductosCompras_proveedor" OWNER TO lubricantes_db_30om_user;

--
-- Name: ProductosCompras_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public."ProductosCompras_proveedor" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductosCompras_proveedor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductosVentas_detalleventa; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public."ProductosVentas_detalleventa" (
    id bigint NOT NULL,
    cantidad numeric(10,3) NOT NULL,
    precio_unitario numeric(12,2) NOT NULL,
    impuesto numeric(12,2) NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    descuento numeric(12,2) NOT NULL,
    articulo_id bigint NOT NULL,
    venta_id bigint NOT NULL
);


ALTER TABLE public."ProductosVentas_detalleventa" OWNER TO lubricantes_db_30om_user;

--
-- Name: ProductosVentas_detalleventa_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public."ProductosVentas_detalleventa" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductosVentas_detalleventa_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductosVentas_venta; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public."ProductosVentas_venta" (
    id bigint NOT NULL,
    codigo character varying(20) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    impuesto numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL,
    estado character varying(20) NOT NULL,
    metodo_pago character varying(20),
    observaciones text NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    cliente_id bigint,
    creado_por_id bigint NOT NULL
);


ALTER TABLE public."ProductosVentas_venta" OWNER TO lubricantes_db_30om_user;

--
-- Name: ProductosVentas_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public."ProductosVentas_venta" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductosVentas_venta_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_articulo; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_articulo (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    codigo_barras character varying(100),
    nombre character varying(200) NOT NULL,
    descripcion text NOT NULL,
    marca character varying(100) NOT NULL,
    modelo character varying(100) NOT NULL,
    imagen character varying(100),
    stock_actual numeric(12,2) NOT NULL,
    stock_minimo numeric(12,2) NOT NULL,
    stock_maximo numeric(12,2),
    unidad_medida character varying(10) NOT NULL,
    costo_promedio numeric(12,2) NOT NULL,
    precio_venta numeric(12,2) NOT NULL,
    tasa_impuesto numeric(4,2) NOT NULL,
    lead_time integer NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    palabras_clave text NOT NULL,
    creado_por_id bigint,
    proveedor_principal_id bigint,
    categoria_id bigint,
    CONSTRAINT aplicacion_articulo_lead_time_check CHECK ((lead_time >= 0))
);


ALTER TABLE public.aplicacion_articulo OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_articulo_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_articulo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_articulo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_categoria; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    descripcion text NOT NULL,
    creado_en timestamp with time zone NOT NULL,
    actualizado_en timestamp with time zone NOT NULL,
    padre_id bigint
);


ALTER TABLE public.aplicacion_categoria OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_cliente; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_cliente (
    id bigint NOT NULL,
    tipo character varying(10) NOT NULL,
    identificacion character varying(20) NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion text NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL
);


ALTER TABLE public.aplicacion_cliente OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_customuser; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    rol character varying(20) NOT NULL,
    telefono character varying(20) NOT NULL,
    direccion text NOT NULL,
    foto_perfil character varying(100),
    admin boolean NOT NULL
);


ALTER TABLE public.aplicacion_customuser OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_customuser_groups; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.aplicacion_customuser_groups OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aplicacion_customuser_user_permissions; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.aplicacion_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.aplicacion_customuser_user_permissions OWNER TO lubricantes_db_30om_user;

--
-- Name: aplicacion_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.aplicacion_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO lubricantes_db_30om_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO lubricantes_db_30om_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO lubricantes_db_30om_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO lubricantes_db_30om_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO lubricantes_db_30om_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO lubricantes_db_30om_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO lubricantes_db_30om_user;

--
-- Data for Name: ProductosCompras_historialstock; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public."ProductosCompras_historialstock" (id, fecha, stock_antes, stock_despues, costo_promedio_antes, costo_promedio_despues, costo_unitario_compra, costo_unitario_anterior, usuario_id, movimiento_id) FROM stdin;
\.


--
-- Data for Name: ProductosCompras_movimientoinventario; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public."ProductosCompras_movimientoinventario" (id, tipo, cantidad, fecha, referencia, observaciones, costo_unitario, articulo_id, usuario_id, proveedor_id) FROM stdin;
\.


--
-- Data for Name: ProductosCompras_proveedor; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public."ProductosCompras_proveedor" (id, nombre, rfc, contacto, telefono, email, direccion, activo, creado_en) FROM stdin;
\.


--
-- Data for Name: ProductosVentas_detalleventa; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public."ProductosVentas_detalleventa" (id, cantidad, precio_unitario, impuesto, subtotal, descuento, articulo_id, venta_id) FROM stdin;
\.


--
-- Data for Name: ProductosVentas_venta; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public."ProductosVentas_venta" (id, codigo, fecha, subtotal, impuesto, total, estado, metodo_pago, observaciones, fecha_creacion, fecha_actualizacion, cliente_id, creado_por_id) FROM stdin;
\.


--
-- Data for Name: aplicacion_articulo; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_articulo (id, codigo, codigo_barras, nombre, descripcion, marca, modelo, imagen, stock_actual, stock_minimo, stock_maximo, unidad_medida, costo_promedio, precio_venta, tasa_impuesto, lead_time, activo, fecha_creacion, fecha_actualizacion, palabras_clave, creado_por_id, proveedor_principal_id, categoria_id) FROM stdin;
5	LLM-000001	7597304218055	Multilubs 4T 20w50		Multilubs	4 Tiempos	articulos/4t_Multilubs.jpeg	9.00	3.00	12.00	LT	20000.00	25000.00	0.16	0	t	2025-05-24 21:58:19.397+00	2025-07-28 13:43:34.368+00	Lubricantes, Aceite, 4 tiempos, 4T	2	\N	5
6	LLM-000002	7709381389386	Venoco 4 Tiempos		Venoco	4 Tiempos	articulos/4t_venoco.jpeg	3.00	2.00	\N	UN	25000.00	30000.00	0.16	60	t	2025-05-24 22:10:56.919+00	2025-07-28 13:43:35.777+00	Lubricantes, 4 tiempos, 4T, Venoco	2	\N	5
7	LLM-000003	7593186002157	KRS 4 Tiempos		KRS	4 Tiempos	articulos/4t_Krs.jpeg	12.00	3.00	12.00	LT	25800.00	30000.00	0.16	15	t	2025-05-24 22:25:52.851+00	2025-07-28 13:43:33.874+00	Lubricantes, 4T, 4 Tiempos	2	\N	5
8	LLM-000004	7592381001040	Inca 4 Tiempos 15w50 Semisintetico		Inca	4 Tiempos	articulos/Inca_4t_15w50.jpeg	11.00	3.00	12.00	LT	32600.00	38000.00	0.16	15	t	2025-05-24 22:29:55.674+00	2025-07-28 17:07:09.431+00	Lubricantes, semisintetico, 15w50, 4T, 4 Tiempos	2	\N	5
9	LLM-000005	7592381000432	Inca 4 Tiempos 20w50		Inca	4 Tiempos	articulos/Inca_4t_20w50.jpeg	6.00	3.00	12.00	LT	29000.00	35000.00	0.16	15	t	2025-05-24 22:35:48.224+00	2025-07-28 13:43:32.874+00	Semisintetico, Lubricantes, 4 Tiempos, 4T	2	\N	5
10	LLM-000006	7593597001343	SKY 4T  25W60		SKY	4 Tiempos	articulos/4t_Sky_25w60.jpeg	9.00	3.00	12.00	LT	28700.00	30000.00	0.16	15	t	2025-05-24 22:39:54.943+00	2025-07-28 13:43:34.824+00		2	\N	5
11	LLM-000007	7593597000056	SKY 4T 20W50		SKY	4 Tiempos	articulos/4t_Sky_20w50.jpeg	8.00	3.00	12.00	LT	28700.00	30000.00	0.16	15	t	2025-05-24 22:41:55.134+00	2025-07-28 13:43:35.298+00		2	\N	5
12	LLM-000008	7593891001490	OILVEN 2T	ACEITE  2T	OILVEN	2T	articulos/OILVEN.jpeg	7.00	3.00	12.00	LT	24000.00	30000.00	0.16	15	t	2025-09-13 18:22:17.084163+00	2025-09-13 18:22:17.08418+00	2T, OILVEN, LUBRICANTE	1	\N	6
13	LLM-000009	0749565938389	ROYAL	2T ROYAL	ROYAL	2T	articulos/ROYAL.jpeg	9.00	3.00	12.00	LT	19000.00	25000.00	0.16	25	t	2025-09-13 18:25:14.454407+00	2025-09-13 18:25:14.454425+00	2T.ROYAL.LUBRICANTE	1	\N	6
15	LLM-0000011	7592381000050	INCA	2T	INCA	2T	articulos/INCA.jpeg	3.00	3.00	12.00	LT	30000.00	35000.00	0.16	0	t	2025-09-13 18:30:13.049452+00	2025-09-13 18:30:13.049468+00	2T, INCA LUBRICANTE	1	\N	6
16	LLM-0000012	\N	LUBRITEC	2T	LUBRITEC	2T	articulos/LUBRITEC.jpeg	5.00	3.00	12.00	LT	16000.00	20000.00	0.16	20	t	2025-09-13 18:33:12.537735+00	2025-09-13 18:33:12.537752+00	2T, LUBRITEC, LUBRICANTE	1	\N	6
17	LLM-0000013	0761371539383	LIGA DE FRENO	LIGA DE FRENO	ROYAL	DOT4	articulos/LIGA_500ML_DOT4.jpeg	22.00	3.00	24.00	LT	10000.00	15000.00	0.16	20	t	2025-09-13 18:39:06.627475+00	2025-09-13 18:39:06.627491+00	LIGA, FRENO, ROYAL	1	\N	7
18	LLM-0000014	4036021889474	LIGA MANNOL	LIGA FRENO	MANNOL	LIGA FRENO	articulos/LIGA_LITRO__DOT4.jpeg	4.00	2.00	12.00	LT	26000.00	30000.00	0.16	20	t	2025-09-13 18:41:34.304112+00	2025-09-13 18:41:34.30413+00	LIGA, FRENO, LITRO	1	\N	7
19	LLM-0000015	7591218023863	FREEZING	LIGA	FREEZING	DOT3	articulos/LIGA_LITRO.jpeg	3.00	3.00	12.00	LT	16000.00	20000.00	0.16	20	t	2025-09-13 18:44:06.338332+00	2025-09-13 18:44:06.338349+00	LIGA, LITRO, DOT3	1	\N	7
14	LLM-0000010	7593186000849	LMV	2T	LMV	2T	articulos/LMV.jpeg	4.00	3.00	12.00	LT	21000.00	25000.00	0.16	15	t	2025-09-13 18:27:27.882089+00	2025-09-13 18:46:25.358615+00	2T, LMV . LUBRICANTE	1	\N	6
\.


--
-- Data for Name: aplicacion_categoria; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_categoria (id, nombre, slug, descripcion, creado_en, actualizado_en, padre_id) FROM stdin;
4	Lubricantes	lubricantes		2025-05-24 21:32:07.969+00	2025-05-24 21:32:07.97+00	\N
5	4 Tiempos	4-tiempos		2025-05-24 21:32:29.249+00	2025-05-24 21:32:29.249+00	4
6	2 Tiempos	2-tiempos		2025-09-13 18:03:29.35474+00	2025-09-13 18:03:29.354754+00	4
7	LIGA DE FRENO	liga-de-freno		2025-09-13 18:36:01.528681+00	2025-09-13 18:36:01.528694+00	\N
\.


--
-- Data for Name: aplicacion_cliente; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_cliente (id, tipo, identificacion, nombre, direccion, telefono, email, activo, fecha_creacion) FROM stdin;
\.


--
-- Data for Name: aplicacion_customuser; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, rol, telefono, direccion, foto_perfil, admin) FROM stdin;
2	pbkdf2_sha256$870000$WwoGixmHxEUyB2gcXG0Tx4$/NefENnemIMG0V8BR8lDvuo2RBsnpIT9Of1HGZqy7gA=	2025-07-28 13:45:05.345+00	t	BrigithK	Brigith	Katherine	kate.2021@hotmail.com	t	t	2025-04-12 20:58:59+00	admin	04262298057	El milagro		t
4	pbkdf2_sha256$870000$Udo3pYWfCGKl6SAJuVowTf$c6zaZTSQNzCqSsPrMpkCHtRkTLvJ/9hKqibHrewaGbs=	2025-04-28 21:40:59.726+00	f	CristopherM	Cristopher	Mora	cristopher.mora08@hotmail.com	t	t	2025-04-18 21:01:41+00	admin	04162721871	El milagro	perfiles/Imagen_de_WhatsApp_2025-04-28_a_las_17.37.28_137c5abe.jpg	f
1	pbkdf2_sha256$1000000$YnAnyKerwJffja1aZmRHJQ$9AtSh/BPVponi4PdMCSBjNr7vvFROchff1uh4VrDA9c=	2025-09-13 18:01:29.033665+00	t	Admin	Anthony	Mora	anthonymorag10@gmail.com	t	t	2025-04-12 19:42:49+00	admin	04161719586	San Cristobal	perfiles/wallpaperflare.com_wallpaper_2.jpg	t
\.


--
-- Data for Name: aplicacion_customuser_groups; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: aplicacion_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.aplicacion_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	7
8	1	8
9	1	9
10	1	10
11	1	11
12	1	12
13	1	13
14	1	14
15	1	15
16	1	16
17	1	17
18	1	18
19	1	19
20	1	20
21	1	21
22	1	22
23	1	23
24	1	24
25	1	25
26	1	26
27	1	27
28	1	28
29	1	29
30	1	30
31	1	31
32	1	32
33	1	33
34	1	34
35	1	35
36	1	36
37	1	37
38	1	38
39	1	39
40	1	40
41	1	41
42	1	42
43	1	43
44	1	44
45	1	45
46	1	46
47	1	47
48	1	48
49	1	49
50	1	50
51	1	51
52	1	52
53	1	53
54	1	54
55	1	55
56	1	56
57	2	1
58	2	2
59	2	3
60	2	4
61	2	5
62	2	6
63	2	7
64	2	8
65	2	9
66	2	10
67	2	11
68	2	12
69	2	13
70	2	14
71	2	15
72	2	16
73	2	17
74	2	18
75	2	19
76	2	20
77	2	21
78	2	22
79	2	23
80	2	24
81	2	25
82	2	26
83	2	27
84	2	28
85	2	29
86	2	30
87	2	31
88	2	32
89	2	33
90	2	34
91	2	35
92	2	36
93	2	37
94	2	38
95	2	39
96	2	40
97	2	41
98	2	42
99	2	43
100	2	44
101	2	45
102	2	46
103	2	47
104	2	48
105	2	49
106	2	50
107	2	51
108	2	52
109	2	53
110	2	54
111	2	55
112	2	56
113	4	36
114	4	40
115	4	8
116	4	12
117	4	28
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Cliente	6	add_cliente
22	Can change Cliente	6	change_cliente
23	Can delete Cliente	6	delete_cliente
24	Can view Cliente	6	view_cliente
25	Can add Usuario	7	add_customuser
26	Can change Usuario	7	change_customuser
27	Can delete Usuario	7	delete_customuser
28	Can view Usuario	7	view_customuser
29	Can add Categoría	8	add_categoria
30	Can change Categoría	8	change_categoria
31	Can delete Categoría	8	delete_categoria
32	Can view Categoría	8	view_categoria
33	Can add Artículo	9	add_articulo
34	Can change Artículo	9	change_articulo
35	Can delete Artículo	9	delete_articulo
36	Can view Artículo	9	view_articulo
37	Can add Detalle de venta	10	add_detalleventa
38	Can change Detalle de venta	10	change_detalleventa
39	Can delete Detalle de venta	10	delete_detalleventa
40	Can view Detalle de venta	10	view_detalleventa
41	Can add Venta	11	add_venta
42	Can change Venta	11	change_venta
43	Can delete Venta	11	delete_venta
44	Can view Venta	11	view_venta
45	Can add historial stock	12	add_historialstock
46	Can change historial stock	12	change_historialstock
47	Can delete historial stock	12	delete_historialstock
48	Can view historial stock	12	view_historialstock
49	Can add Movimiento de Inventario	13	add_movimientoinventario
50	Can change Movimiento de Inventario	13	change_movimientoinventario
51	Can delete Movimiento de Inventario	13	delete_movimientoinventario
52	Can view Movimiento de Inventario	13	view_movimientoinventario
53	Can add Proveedor	14	add_proveedor
54	Can change Proveedor	14	change_proveedor
55	Can delete Proveedor	14	delete_proveedor
56	Can view Proveedor	14	view_proveedor
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-09-13 18:03:29.357623+00	6	2 Tiempos	1	[{"added": {}}]	8	1
2	2025-09-13 18:36:01.530598+00	7	LIGA DE FRENO	1	[{"added": {}}]	8	1
3	2025-09-13 18:46:25.361938+00	14	LLM-0000010 - LMV	2	[{"changed": {"fields": ["C\\u00f3digo"]}}]	9	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	aplicacion	cliente
7	aplicacion	customuser
8	aplicacion	categoria
9	aplicacion	articulo
10	ProductosVentas	detalleventa
11	ProductosVentas	venta
12	ProductosCompras	historialstock
13	ProductosCompras	movimientoinventario
14	ProductosCompras	proveedor
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-13 13:50:51.234443+00
2	contenttypes	0002_remove_content_type_name	2025-09-13 13:50:51.815923+00
3	auth	0001_initial	2025-09-13 13:50:53.705049+00
4	auth	0002_alter_permission_name_max_length	2025-09-13 13:50:54.025119+00
5	auth	0003_alter_user_email_max_length	2025-09-13 13:50:54.261494+00
6	auth	0004_alter_user_username_opts	2025-09-13 13:50:54.899447+00
7	auth	0005_alter_user_last_login_null	2025-09-13 13:50:55.298406+00
8	auth	0006_require_contenttypes_0002	2025-09-13 13:50:55.660341+00
9	auth	0007_alter_validators_add_error_messages	2025-09-13 13:50:56.388074+00
10	auth	0008_alter_user_username_max_length	2025-09-13 13:50:56.746204+00
11	auth	0009_alter_user_last_name_max_length	2025-09-13 13:50:57.079724+00
12	auth	0010_alter_group_name_max_length	2025-09-13 13:50:57.674418+00
13	auth	0011_update_proxy_permissions	2025-09-13 13:50:57.914866+00
14	auth	0012_alter_user_first_name_max_length	2025-09-13 13:50:58.272456+00
15	ProductosCompras	0001_initial	2025-09-13 13:50:59.118747+00
16	aplicacion	0001_initial	2025-09-13 13:51:04.752024+00
17	ProductosCompras	0002_initial	2025-09-13 13:51:06.855446+00
18	ProductosVentas	0001_initial	2025-09-13 13:51:07.5503+00
19	ProductosVentas	0002_initial	2025-09-13 13:51:08.934887+00
20	admin	0001_initial	2025-09-13 13:51:09.824008+00
21	admin	0002_logentry_remove_auto_add	2025-09-13 13:51:09.968957+00
22	admin	0003_logentry_add_action_flag_choices	2025-09-13 13:51:10.32885+00
23	sessions	0001_initial	2025-09-13 13:51:11.14636+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: lubricantes_db_30om_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
vley0vef92noo1wkamfsrl1lnohcb6sg	.eJxVjEEOwiAQRe_C2pACU1pcuu8ZyDAzSNXQpLQr491Nky50-997_60i7luJe5M1zqyuyqjL75aQnlIPwA-s90XTUrd1TvpQ9EmbnhaW1-10_w4KtnLUJB14JpZhcKML0CXLgAh9DzLgOFI26B0Bg_Mm5OAIXfbBircm90l9vvGdOAo:1uxQqX:q11M0Ott7fXNfeJECCgr3GyriUIaxx_mlUS4_wkWK-I	2025-09-27 14:03:21.204805+00
z68uyo62i2a7u44mj4z89aowu71n8n66	.eJxVjEEOwiAQRe_C2pACU1pcuu8ZyDAzSNXQpLQr491Nky50-997_60i7luJe5M1zqyuyqjL75aQnlIPwA-s90XTUrd1TvpQ9EmbnhaW1-10_w4KtnLUJB14JpZhcKML0CXLgAh9DzLgOFI26B0Bg_Mm5OAIXfbBircm90l9vvGdOAo:1uxUYz:y55Q3eleTEBzsC3zVP2aY7Rm8DwOs60HFIWFHsYLU0A	2025-09-27 18:01:29.03871+00
\.


--
-- Name: ProductosCompras_historialstock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public."ProductosCompras_historialstock_id_seq"', 1, false);


--
-- Name: ProductosCompras_movimientoinventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public."ProductosCompras_movimientoinventario_id_seq"', 1, false);


--
-- Name: ProductosCompras_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public."ProductosCompras_proveedor_id_seq"', 1, false);


--
-- Name: ProductosVentas_detalleventa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public."ProductosVentas_detalleventa_id_seq"', 1, false);


--
-- Name: ProductosVentas_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public."ProductosVentas_venta_id_seq"', 1, false);


--
-- Name: aplicacion_articulo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_articulo_id_seq', 19, true);


--
-- Name: aplicacion_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_categoria_id_seq', 7, true);


--
-- Name: aplicacion_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_cliente_id_seq', 1, false);


--
-- Name: aplicacion_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_customuser_groups_id_seq', 1, false);


--
-- Name: aplicacion_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_customuser_id_seq', 4, true);


--
-- Name: aplicacion_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.aplicacion_customuser_user_permissions_id_seq', 117, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lubricantes_db_30om_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 23, true);


--
-- Name: ProductosCompras_historialstock ProductosCompras_historialstock_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_historialstock"
    ADD CONSTRAINT "ProductosCompras_historialstock_pkey" PRIMARY KEY (id);


--
-- Name: ProductosCompras_movimientoinventario ProductosCompras_movimientoinventario_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_movimientoinventario"
    ADD CONSTRAINT "ProductosCompras_movimientoinventario_pkey" PRIMARY KEY (id);


--
-- Name: ProductosCompras_proveedor ProductosCompras_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_proveedor"
    ADD CONSTRAINT "ProductosCompras_proveedor_pkey" PRIMARY KEY (id);


--
-- Name: ProductosVentas_detalleventa ProductosVentas_detalleventa_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_detalleventa"
    ADD CONSTRAINT "ProductosVentas_detalleventa_pkey" PRIMARY KEY (id);


--
-- Name: ProductosVentas_venta ProductosVentas_venta_codigo_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_venta"
    ADD CONSTRAINT "ProductosVentas_venta_codigo_key" UNIQUE (codigo);


--
-- Name: ProductosVentas_venta ProductosVentas_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_venta"
    ADD CONSTRAINT "ProductosVentas_venta_pkey" PRIMARY KEY (id);


--
-- Name: aplicacion_articulo aplicacion_articulo_codigo_barras_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT aplicacion_articulo_codigo_barras_key UNIQUE (codigo_barras);


--
-- Name: aplicacion_articulo aplicacion_articulo_codigo_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT aplicacion_articulo_codigo_key UNIQUE (codigo);


--
-- Name: aplicacion_articulo aplicacion_articulo_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT aplicacion_articulo_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_categoria aplicacion_categoria_nombre_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_categoria
    ADD CONSTRAINT aplicacion_categoria_nombre_key UNIQUE (nombre);


--
-- Name: aplicacion_categoria aplicacion_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_categoria
    ADD CONSTRAINT aplicacion_categoria_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_categoria aplicacion_categoria_slug_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_categoria
    ADD CONSTRAINT aplicacion_categoria_slug_key UNIQUE (slug);


--
-- Name: aplicacion_cliente aplicacion_cliente_identificacion_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_cliente
    ADD CONSTRAINT aplicacion_cliente_identificacion_key UNIQUE (identificacion);


--
-- Name: aplicacion_cliente aplicacion_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_cliente
    ADD CONSTRAINT aplicacion_cliente_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_customuser_groups aplicacion_customuser_gr_customuser_id_group_id_95b4f5ab_uniq; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_groups
    ADD CONSTRAINT aplicacion_customuser_gr_customuser_id_group_id_95b4f5ab_uniq UNIQUE (customuser_id, group_id);


--
-- Name: aplicacion_customuser_groups aplicacion_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_groups
    ADD CONSTRAINT aplicacion_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_customuser aplicacion_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser
    ADD CONSTRAINT aplicacion_customuser_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_customuser_user_permissions aplicacion_customuser_us_customuser_id_permission_c9cee199_uniq; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_user_permissions
    ADD CONSTRAINT aplicacion_customuser_us_customuser_id_permission_c9cee199_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: aplicacion_customuser_user_permissions aplicacion_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_user_permissions
    ADD CONSTRAINT aplicacion_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: aplicacion_customuser aplicacion_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser
    ADD CONSTRAINT aplicacion_customuser_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: ProductosCompras_historialstock_movimiento_id_6f5c1ea4; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosCompras_historialstock_movimiento_id_6f5c1ea4" ON public."ProductosCompras_historialstock" USING btree (movimiento_id);


--
-- Name: ProductosCompras_historialstock_usuario_id_a3cfc57f; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosCompras_historialstock_usuario_id_a3cfc57f" ON public."ProductosCompras_historialstock" USING btree (usuario_id);


--
-- Name: ProductosCompras_movimientoinventario_articulo_id_1f253efc; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosCompras_movimientoinventario_articulo_id_1f253efc" ON public."ProductosCompras_movimientoinventario" USING btree (articulo_id);


--
-- Name: ProductosCompras_movimientoinventario_proveedor_id_1b2806e0; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosCompras_movimientoinventario_proveedor_id_1b2806e0" ON public."ProductosCompras_movimientoinventario" USING btree (proveedor_id);


--
-- Name: ProductosCompras_movimientoinventario_usuario_id_5fd4c159; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosCompras_movimientoinventario_usuario_id_5fd4c159" ON public."ProductosCompras_movimientoinventario" USING btree (usuario_id);


--
-- Name: ProductosVentas_detalleventa_articulo_id_c8be6eff; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosVentas_detalleventa_articulo_id_c8be6eff" ON public."ProductosVentas_detalleventa" USING btree (articulo_id);


--
-- Name: ProductosVentas_detalleventa_venta_id_eb61244e; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosVentas_detalleventa_venta_id_eb61244e" ON public."ProductosVentas_detalleventa" USING btree (venta_id);


--
-- Name: ProductosVentas_venta_cliente_id_546364c9; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosVentas_venta_cliente_id_546364c9" ON public."ProductosVentas_venta" USING btree (cliente_id);


--
-- Name: ProductosVentas_venta_codigo_61896a68_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosVentas_venta_codigo_61896a68_like" ON public."ProductosVentas_venta" USING btree (codigo varchar_pattern_ops);


--
-- Name: ProductosVentas_venta_creado_por_id_ff275886; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX "ProductosVentas_venta_creado_por_id_ff275886" ON public."ProductosVentas_venta" USING btree (creado_por_id);


--
-- Name: aplicacion__activo_9aa009_idx; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion__activo_9aa009_idx ON public.aplicacion_articulo USING btree (activo);


--
-- Name: aplicacion__categor_4c6326_idx; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion__categor_4c6326_idx ON public.aplicacion_articulo USING btree (categoria_id);


--
-- Name: aplicacion__codigo_24ae83_idx; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion__codigo_24ae83_idx ON public.aplicacion_articulo USING btree (codigo);


--
-- Name: aplicacion__nombre_a0c344_idx; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion__nombre_a0c344_idx ON public.aplicacion_articulo USING btree (nombre);


--
-- Name: aplicacion_articulo_categoria_id_a4cda406; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_articulo_categoria_id_a4cda406 ON public.aplicacion_articulo USING btree (categoria_id);


--
-- Name: aplicacion_articulo_codigo_b100686c_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_articulo_codigo_b100686c_like ON public.aplicacion_articulo USING btree (codigo varchar_pattern_ops);


--
-- Name: aplicacion_articulo_codigo_barras_725fade3_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_articulo_codigo_barras_725fade3_like ON public.aplicacion_articulo USING btree (codigo_barras varchar_pattern_ops);


--
-- Name: aplicacion_articulo_creado_por_id_124abc61; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_articulo_creado_por_id_124abc61 ON public.aplicacion_articulo USING btree (creado_por_id);


--
-- Name: aplicacion_articulo_proveedor_principal_id_7ef2620f; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_articulo_proveedor_principal_id_7ef2620f ON public.aplicacion_articulo USING btree (proveedor_principal_id);


--
-- Name: aplicacion_categoria_nombre_d34988fd_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_categoria_nombre_d34988fd_like ON public.aplicacion_categoria USING btree (nombre varchar_pattern_ops);


--
-- Name: aplicacion_categoria_padre_id_70740de0; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_categoria_padre_id_70740de0 ON public.aplicacion_categoria USING btree (padre_id);


--
-- Name: aplicacion_categoria_slug_59596c6e_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_categoria_slug_59596c6e_like ON public.aplicacion_categoria USING btree (slug varchar_pattern_ops);


--
-- Name: aplicacion_cliente_identificacion_5b5d66f3_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_cliente_identificacion_5b5d66f3_like ON public.aplicacion_cliente USING btree (identificacion varchar_pattern_ops);


--
-- Name: aplicacion_customuser_groups_customuser_id_cf324d32; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_customuser_groups_customuser_id_cf324d32 ON public.aplicacion_customuser_groups USING btree (customuser_id);


--
-- Name: aplicacion_customuser_groups_group_id_d8b23004; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_customuser_groups_group_id_d8b23004 ON public.aplicacion_customuser_groups USING btree (group_id);


--
-- Name: aplicacion_customuser_user_permissions_customuser_id_dd4914d8; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_customuser_user_permissions_customuser_id_dd4914d8 ON public.aplicacion_customuser_user_permissions USING btree (customuser_id);


--
-- Name: aplicacion_customuser_user_permissions_permission_id_eb296d69; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_customuser_user_permissions_permission_id_eb296d69 ON public.aplicacion_customuser_user_permissions USING btree (permission_id);


--
-- Name: aplicacion_customuser_username_623bc97b_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX aplicacion_customuser_username_623bc97b_like ON public.aplicacion_customuser USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: lubricantes_db_30om_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: ProductosCompras_historialstock ProductosCompras_his_movimiento_id_6f5c1ea4_fk_Productos; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_historialstock"
    ADD CONSTRAINT "ProductosCompras_his_movimiento_id_6f5c1ea4_fk_Productos" FOREIGN KEY (movimiento_id) REFERENCES public."ProductosCompras_movimientoinventario"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosCompras_historialstock ProductosCompras_his_usuario_id_a3cfc57f_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_historialstock"
    ADD CONSTRAINT "ProductosCompras_his_usuario_id_a3cfc57f_fk_aplicacio" FOREIGN KEY (usuario_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosCompras_movimientoinventario ProductosCompras_mov_articulo_id_1f253efc_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_movimientoinventario"
    ADD CONSTRAINT "ProductosCompras_mov_articulo_id_1f253efc_fk_aplicacio" FOREIGN KEY (articulo_id) REFERENCES public.aplicacion_articulo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosCompras_movimientoinventario ProductosCompras_mov_proveedor_id_1b2806e0_fk_Productos; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_movimientoinventario"
    ADD CONSTRAINT "ProductosCompras_mov_proveedor_id_1b2806e0_fk_Productos" FOREIGN KEY (proveedor_id) REFERENCES public."ProductosCompras_proveedor"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosCompras_movimientoinventario ProductosCompras_mov_usuario_id_5fd4c159_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosCompras_movimientoinventario"
    ADD CONSTRAINT "ProductosCompras_mov_usuario_id_5fd4c159_fk_aplicacio" FOREIGN KEY (usuario_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosVentas_detalleventa ProductosVentas_deta_articulo_id_c8be6eff_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_detalleventa"
    ADD CONSTRAINT "ProductosVentas_deta_articulo_id_c8be6eff_fk_aplicacio" FOREIGN KEY (articulo_id) REFERENCES public.aplicacion_articulo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosVentas_detalleventa ProductosVentas_deta_venta_id_eb61244e_fk_Productos; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_detalleventa"
    ADD CONSTRAINT "ProductosVentas_deta_venta_id_eb61244e_fk_Productos" FOREIGN KEY (venta_id) REFERENCES public."ProductosVentas_venta"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosVentas_venta ProductosVentas_vent_cliente_id_546364c9_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_venta"
    ADD CONSTRAINT "ProductosVentas_vent_cliente_id_546364c9_fk_aplicacio" FOREIGN KEY (cliente_id) REFERENCES public.aplicacion_cliente(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ProductosVentas_venta ProductosVentas_vent_creado_por_id_ff275886_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public."ProductosVentas_venta"
    ADD CONSTRAINT "ProductosVentas_vent_creado_por_id_ff275886_fk_aplicacio" FOREIGN KEY (creado_por_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_articulo aplicacion_articulo_categoria_id_a4cda406_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT aplicacion_articulo_categoria_id_a4cda406_fk_aplicacio FOREIGN KEY (categoria_id) REFERENCES public.aplicacion_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_articulo aplicacion_articulo_creado_por_id_124abc61_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT aplicacion_articulo_creado_por_id_124abc61_fk_aplicacio FOREIGN KEY (creado_por_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_articulo aplicacion_articulo_proveedor_principal__7ef2620f_fk_Productos; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_articulo
    ADD CONSTRAINT "aplicacion_articulo_proveedor_principal__7ef2620f_fk_Productos" FOREIGN KEY (proveedor_principal_id) REFERENCES public."ProductosCompras_proveedor"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_categoria aplicacion_categoria_padre_id_70740de0_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_categoria
    ADD CONSTRAINT aplicacion_categoria_padre_id_70740de0_fk_aplicacio FOREIGN KEY (padre_id) REFERENCES public.aplicacion_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_customuser_groups aplicacion_customuse_customuser_id_cf324d32_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_groups
    ADD CONSTRAINT aplicacion_customuse_customuser_id_cf324d32_fk_aplicacio FOREIGN KEY (customuser_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_customuser_user_permissions aplicacion_customuse_customuser_id_dd4914d8_fk_aplicacio; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_user_permissions
    ADD CONSTRAINT aplicacion_customuse_customuser_id_dd4914d8_fk_aplicacio FOREIGN KEY (customuser_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_customuser_user_permissions aplicacion_customuse_permission_id_eb296d69_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_user_permissions
    ADD CONSTRAINT aplicacion_customuse_permission_id_eb296d69_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aplicacion_customuser_groups aplicacion_customuser_groups_group_id_d8b23004_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.aplicacion_customuser_groups
    ADD CONSTRAINT aplicacion_customuser_groups_group_id_d8b23004_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_aplicacion_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: lubricantes_db_30om_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_aplicacion_customuser_id FOREIGN KEY (user_id) REFERENCES public.aplicacion_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: lubricantes_db_30om_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO lubricantes_db_30om_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO lubricantes_db_30om_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO lubricantes_db_30om_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO lubricantes_db_30om_user;


--
-- PostgreSQL database dump complete
--

\unrestrict O2bKGsRucduv3OrUidLxw60wCb6OL0nvCNT02xkaJTnNzVfK2libjuHLAVXoMFr

