# Generated by Django 5.2.5 on 2025-09-13 09:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductosCompras', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICO', 'Persona Jurídica')], default='NATURAL', max_length=10)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('personal', 'Personal'), ('invitado', 'Invitado')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(location='media/'), upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('admin', models.BooleanField(default=False, verbose_name='¿Administrador?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='aplicacion.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(location='media/'), upload_to='articulos/')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro'), ('PAR', 'Par'), ('JUEGO', 'Juego'), ('CAJA', 'Caja')], default='UN', max_length=10)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tasa_impuesto', models.DecimalField(choices=[(Decimal('0.00'), 'Exento'), (Decimal('0.16'), 'IVA 16%'), (Decimal('0.08'), 'IVA 8%')], decimal_places=2, default=Decimal('0.16'), max_digits=4)),
                ('lead_time', models.PositiveIntegerField(default=0, help_text='Tiempo de reposición en días')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('palabras_clave', models.TextField(blank=True, help_text='Ingrese palabras clave separadas por comas. Ej: Toyota, Carro, Automático')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProductosCompras.proveedor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='aplicacion__codigo_24ae83_idx'), models.Index(fields=['nombre'], name='aplicacion__nombre_a0c344_idx'), models.Index(fields=['categoria'], name='aplicacion__categor_4c6326_idx'), models.Index(fields=['activo'], name='aplicacion__activo_9aa009_idx')],
            },
        ),
    ]
