# Generated by Django 5.1.7 on 2025-04-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_cliente_proveedor_remove_customuser_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.cliente'),
        ),
    ]
